### ISSUE TITLE
Header Text Overflowing out of the parent container.

### ISSUE THREAD

**Issue by jatinAroraGit** [smilegodly/whiteboardapp#1]
Hey there, 
The issue I found was that when the app is ran on devices with screen width less than 375 px the Header Text starts to overrun the parent div.
The issue can be reproduced by running the application on Chrome and then inspecting it. In the inspecting windows select "toggle device toolbar" option on top left corner and set device to Galaxy S5.
I would like to work on this issue.
Thanks.
Have a good day.

**Comment by fosteman** [comment]
Works fine for me...
<img width="388" alt="Screen Shot 2019-09-13 at 10 23 45 AM" src="https://user-images.githubusercontent.com/32850517/64870100-a7876580-d610-11e9-9280-08b3a0e62f75.png">

**Comment by jatinAroraGit** [comment]
The repository owner changed the Heading in index.html in this commit https://github.com/smilegodly/whiteboardapp/commit/b15d5c6f8ada83de1056136caf93afbd99e4196a
 Before that the header consisted of a longer text which resulted in text overflowing.
