### ISSUE TITLE
preformatted js code

### ISSUE THREAD

**Issue by fosteman** [smilegodly/whiteboardapp#2]
```{"document":[{"text":[{"type":"string","attributes":{},"string":"Welcome to my notepad!aawd\n"},{"type":"string","attributes":{"blockBreak":true},"string":"\n"}],"attributes":[]}],"selectedRange":[27,27]}```

**Comment by smilegodly** [comment]
I'm confused about what the issue is here.

Could you explain more about what this code is for?

Thanks,

**Comment by fosteman** [comment]
For some reason on local setup I see this instead of the notepad.
<img width="154" alt="Screen Shot 2019-09-13 at 10 23 45 AM" src="https://user-images.githubusercontent.com/32850517/64877022-83cb1c00-d61e-11e9-9a58-e6af71024b32.png">

**Comment by smilegodly** [comment]
I have not been able to replicate this issue.
I've hosted it both on Chrome and Firefox and could not replicate the issue when using the default port on localhost.
Below I have a picture showing that it works on the default localhost.

![image](https://user-images.githubusercontent.com/35276477/64884921-d4e40b80-d630-11e9-8917-b161a5b1469a.png)
