### ISSUE TITLE
Adding "Clear" button

### ISSUE THREAD

**Issue by lozinska** [smilegodly/whiteboardapp#3]
I think it would be nice to add "Clear" button on the page to clear the contents of the note. Please let me know if I can work on it. Thank you

**Comment by smilegodly** [comment]
Sounds good ! 😺 
I have assigned you to the issue. @lozinska 

Have a good day,

**Comment by smilegodly** [comment]
however, I do not want the "Clear" process to be a irreversible one.
For example.. In the case that I accidentally click "Clear", I would still need to be able to restore what I had cleared.
This is to avoid auto-deletion and loss of data in the notepad.

**Comment by lozinska** [comment]
Thank you. Sounds like a good idea

**Comment by lozinska** [comment]
Ok sure ill fix it.Thank you

**Comment by smilegodly** [comment]
You can either do that on github from my repo, or use the command:
git pull

**Comment by lozinska** [comment]
Thank you
